# Generated by Django 4.1.1 on 2022-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="a", max_length=2, verbose_name="category"),
        ),
    ]
