# Generated by Django 4.1.1 on 2022-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_login_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lat",
            field=models.FloatField(blank=True, null=True, verbose_name="lat"),
        ),
        migrations.AddField(
            model_name="user",
            name="long",
            field=models.FloatField(blank=True, null=True, verbose_name="long"),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                default="NoAddress", max_length=100, verbose_name="address_name"
            ),
        ),
    ]
